# -------------------
# TokyoNight Alacritty Colors
# -------------------

# # Default colors
# [colors.primary]
# background = '#1a1b26'
# foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

# -------------------
# Colors (One Dark)
# -------------------

# Default colors
[colors.primary]
background = '#151515'
foreground = '#abb2bf'

# # Normal colors
# [colors.normal]
# black   = '#1e2127'
# red     = '#e06c75'
# green   = '#98c379'
# yellow  = '#d19a66'
# blue    = '#61afef'
# magenta = '#c678dd'
# cyan    = '#56b6c2'
# white   = '#abb2bf'
#
# # Bright colors
# [colors.bright]
# black   = '#5c6370'
# red     = '#e06c75'
# green   = '#98c379'
# yellow  = '#d19a66'
# blue    = '#61afef'
# magenta = '#c678dd'
# cyan    = '#56b6c2'
# white   = '#ffffff'

[cursor]
vi_mode_style = "Block"

[font]
size = 14.5
# normal.family = "VictorMono Nerd Font"
# normal.style = "Light"
# bold.style = "SemiBold"
# bold_italic.style = "SemiBold Oblique"
# italic.style = "Light Oblique"
# offset.x = 1
# offset.y = -3

normal.family = "RobotoMono Nerd Font"
normal.style = "Light"
bold.style = "Medium"
bold_italic.style = "Medium Italic"
italic.style = "Light Italic"
offset.y = -2

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Command"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[mouse]
hide_when_typing = false

[scrolling]
history = 100000

[window]
decorations = "buttonless"
opacity = 0.92
